[metadata]
name = comandi-cli
version = 0.1.0
description = Personal CLI to save and run frequently used shell commands
license = MIT

[options]
packages = find:
include_package_data = True
python_requires = >=3.8
install_requires =
    questionary>=2.0

[options.entry_points]
console_scripts =
    commands = comandi.cli:main

[options.package_data]
comandi = data/commands.json
